"""High-level three-body decay-model construction."""

from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, fields, is_dataclass
from itertools import permutations
from typing import Literal

import jax.numpy as jnp

from jaxpwa.amplitude import (
    AmplitudeComponent,
    CoherentAmplitudeModel,
    ConstantAmplitude,
    PreparedAmplitudeCache,
)
from jaxpwa.amplitude.cache import DEFAULT_NORMALIZATION_CHUNK_SIZE
from jaxpwa.amplitude.components import coefficient_value
from jaxpwa.dynamics import (
    CovariantAngular,
    RelativisticBreitWigner,
    ResonanceAmplitude,
    ResonanceContext,
)
from jaxpwa.dynamics.context import resolve_value
from jaxpwa.fit import Parameter, ParameterKind
from jaxpwa.fit.parameters import _fixed_parameter_updates, _replace_fixed_parameters
from jaxpwa.integration import (
    AdaptiveDalitzGaussLegendreGrid,
    DalitzGaussLegendreGrid,
    GridIntegrator,
)
from jaxpwa.integration.adaptive_square_dalitz import AdaptiveSquareDalitzGrid
from jaxpwa.kinematics import PhaseSpaceMC, PhaseSpaceSample, SquareDalitzGrid
from jaxpwa.observables.errors import _covariance_matrix
from jaxpwa.particle_properties import (
    mass_gev as _mass_gev,
)
from jaxpwa.particle_properties import (
    resolve_particle as _particle,
)
from jaxpwa.particle_properties import (
    resolve_resonance_properties as _resolve_resonance_properties,
)
from jaxpwa.pdf import SignalPDF


def _collect_parameters(value: object) -> tuple[Parameter, ...]:
    """Recursively collect fit Parameters from model declarations/plugins."""

    if isinstance(value, Parameter):
        return (value,)
    parameters = getattr(value, "parameters", None)
    if parameters is not None and not callable(parameters):
        if isinstance(parameters, dict):
            return tuple(
                item for item in parameters.values() if isinstance(item, Parameter)
            )
        try:
            return tuple(item for item in parameters if isinstance(item, Parameter))
        except TypeError:
            pass
    if is_dataclass(value) and not isinstance(value, type):
        found = []
        for field in fields(value):
            found.extend(_collect_parameters(getattr(value, field.name)))
        return tuple(found)
    if isinstance(value, dict):
        return tuple(
            parameter
            for item in value.values()
            for parameter in _collect_parameters(item)
        )
    if isinstance(value, (tuple, list)):
        return tuple(
            parameter for item in value for parameter in _collect_parameters(item)
        )
    return ()


def _nominal_float(value: object | None, fallback: float) -> float:
    """Resolve the nominal numerical value used to freeze an integration scheme."""

    if value is None:
        return float(fallback)
    if isinstance(value, Parameter):
        return float(value.value)
    return float(value)


def _symmetrized_mass_pairs(
    pair: tuple[int, int],
    final_state_ids: tuple[int, int, int],
) -> tuple[tuple[int, int], ...]:
    """Return invariant-mass pairs generated by identical-particle symmetry."""

    unique: set[tuple[int, int]] = set()
    for permutation in permutations(range(3)):
        if all(
            final_state_ids[index] == final_state_ids[permutation[index]]
            for index in range(3)
        ):
            mapped = tuple(sorted(permutation[index] for index in pair))
            unique.add(mapped)
    return tuple(sorted(unique))


def _validate_positive_quantity(value: object, label: str, *, allow_zero: bool) -> None:
    parameter = value if isinstance(value, Parameter) else None
    nominal = float(parameter.value if parameter is not None else value)
    invalid = nominal < 0.0 if allow_zero else nominal <= 0.0
    if invalid:
        comparator = "non-negative" if allow_zero else "positive"
        raise ValueError(f"{label} must be {comparator}, got {nominal}")

    if parameter is not None and parameter.bounds is not None:
        lower, _ = parameter.bounds
        if lower is not None:
            invalid_lower = lower < 0.0 if allow_zero else lower <= 0.0
            if invalid_lower:
                comparator = "non-negative" if allow_zero else "positive"
                raise ValueError(
                    f"lower bound for {label} must be {comparator}, got {lower}"
                )


@dataclass(frozen=True)
class DecayChannel:
    """Parent particle and ordered three-body final state."""

    parent: str
    final_state: tuple[str, str, str]

    def __post_init__(self) -> None:
        if len(self.final_state) != 3:
            raise ValueError("DecayChannel requires exactly three final-state particles")
        if self.parent_mass <= sum(self.daughter_masses):
            raise ValueError(
                "parent mass must exceed the sum of final-state masses for a physical three-body decay"
            )

    @classmethod
    def from_particles(
        cls, parent: str, final_state: Sequence[str]
    ) -> DecayChannel:
        """Build a three-body channel from names in the particle database."""
        return cls(parent, tuple(final_state))

    @property
    def parent_mass(self) -> float:
        """Parent particle mass in GeV, looked up by name from `particle`."""
        return _mass_gev(self.parent)

    @property
    def daughter_masses(self) -> tuple[float, float, float]:
        """Final-state masses in GeV, in `final_state` order."""
        return tuple(_mass_gev(name) for name in self.final_state)

    @property
    def final_state_ids(self) -> tuple[int, int, int]:
        """PDG IDs of the final-state particles, in `final_state` order."""
        return tuple(int(_particle(name).pdgid) for name in self.final_state)


@dataclass(frozen=True)
class Resonance:
    """Declarative resonance component with interchangeable dynamics plugins.

    ``normalize_form_factors=True`` makes both amplitude barriers unity at
    the pole. False uses raw Laura++ primed barriers. This is independent of
    ``normalize_component`` (unit-integral component rescaling) and does not
    change the barrier ratio in the running width.
    """

    name: str
    pair: tuple[int, int]
    coefficient: object
    lineshape: object = RelativisticBreitWigner()
    angular: object = CovariantAngular()
    mass: object | None = None
    width: object | None = None
    spin: int | None = None
    resonance_radius: object = 1.5
    parent_radius: object = 5.0
    bachelor_momentum_frame: Literal["resonance", "parent"] = "resonance"
    normalize_component: bool | None = None
    normalize_form_factors: bool = True
    particle_name: str | None = None

    def __post_init__(self) -> None:
        if len(set(self.pair)) != 2 or any(
            index not in (0, 1, 2) for index in self.pair
        ):
            raise ValueError(
                "resonance pair must contain two distinct indices from 0, 1, 2"
            )
        if self.mass is not None:
            _validate_positive_quantity(self.mass, f"{self.name}.mass", allow_zero=False)
        if self.width is not None:
            _validate_positive_quantity(self.width, f"{self.name}.width", allow_zero=True)
        _validate_positive_quantity(self.resonance_radius, f"{self.name}.resonance_radius", allow_zero=True)
        _validate_positive_quantity(self.parent_radius, f"{self.name}.parent_radius", allow_zero=True)
        if self.spin is not None and (self.spin < 0 or int(self.spin) != self.spin):
            raise ValueError("resonance spin must be a non-negative integer")
        if self.bachelor_momentum_frame not in {"resonance", "parent"}:
            raise ValueError(
                "bachelor_momentum_frame must be either 'resonance' or 'parent'"
            )
        if self.normalize_component is not None and not isinstance(
            self.normalize_component, bool
        ):
            raise ValueError("normalize_component must be a boolean or None")
        if self.particle_name is not None and (
            not isinstance(self.particle_name, str) or not self.particle_name
        ):
            raise ValueError("particle_name must be a nonempty string or None")

    @classmethod
    def from_particle(
        cls,
        particle_name: str,
        *,
        pair: tuple[int, int],
        coefficient: object,
        name: str | None = None,
        lineshape: object = RelativisticBreitWigner(),
        angular: object = CovariantAngular(),
        mass: object | None = None,
        width: object | None = None,
        spin: int | None = None,
        resonance_radius: object = 1.5,
        parent_radius: object = 5.0,
        bachelor_momentum_frame: Literal["resonance", "parent"] = "resonance",
        normalize_component: bool | None = None,
        normalize_form_factors: bool = True,
    ) -> Resonance:
        """Build a resonance from the same particle lookup used by ``Isobar``.

        Explicit mass, width and spin values take precedence. ``name`` may set
        a distinct amplitude-component name while ``particle_name`` retains the
        database identity used for provenance and unresolved properties.
        """
        resolved_mass, resolved_width, resolved_spin = _resolve_resonance_properties(
            particle_name,
            mass=mass,
            width=width,
            spin=spin,
            context="Three-body resonance component",
            validate_name=True,
        )
        return cls(
            name=particle_name if name is None else name,
            pair=pair,
            coefficient=coefficient,
            lineshape=lineshape,
            angular=angular,
            mass=resolved_mass,
            width=resolved_width,
            spin=resolved_spin,
            resonance_radius=resonance_radius,
            parent_radius=parent_radius,
            bachelor_momentum_frame=bachelor_momentum_frame,
            normalize_component=normalize_component,
            normalize_form_factors=normalize_form_factors,
            particle_name=particle_name,
        )


def _resolved_resonance_properties(
    component: Resonance,
) -> tuple[object, object, int]:
    particle_name = component.particle_name or component.name
    return _resolve_resonance_properties(
        particle_name,
        mass=component.mass,
        width=component.width,
        spin=component.spin,
        context="Three-body resonance component",
        validate_name=component.particle_name is not None,
    )


@dataclass(frozen=True)
class NonResonant:
    coefficient: object
    name: str = "NR"
    normalize_component: bool | None = None

    def __post_init__(self) -> None:
        if self.normalize_component is not None and not isinstance(
            self.normalize_component, bool
        ):
            raise ValueError("normalize_component must be a boolean or None")


@dataclass(frozen=True)
class DalitzAmplitude:
    """Direct amplitude depending on two Dalitz coordinates.

    This declaration is intended for dynamics such as ``QMI2D`` that are not a
    one-dimensional isobar lineshape and therefore act directly on the event's
    Dalitz invariants.
    """

    name: str
    dynamics: object
    coefficient: object
    normalize_component: bool | None = None

    def __post_init__(self) -> None:
        if self.normalize_component is not None and not isinstance(
            self.normalize_component, bool
        ):
            raise ValueError("normalize_component must be a boolean or None")


@dataclass(frozen=True)
class _ResolvedDirectDynamics:
    dynamics: object

    def __call__(self, data, parameters=None):
        return resolve_value(self.dynamics, parameters)(data)

    def compact_prepared_data(self, data):
        """Delegate to the wrapped dynamics object when it can compact itself."""

        compact = getattr(self.dynamics, "compact_prepared_data", None)
        return dict(data) if compact is None else compact(data)


@dataclass(frozen=True, init=False)
class DecayModel:
    """Build a coherent amplitude model with deterministic DP normalization.

    Parameters
    ----------
    channel:
        Three-body decay channel defining masses, particle ordering, and the
        kinematic Dalitz-plot boundary.
    components:
        Coherent amplitude components: Resonance, NonResonant, or
        DalitzAmplitude objects.
    normalize_components:
        If True, each dynamical component is individually scaled by
        1/sqrt(integral |F_i|^2 dPhi) before its complex coefficient is
        applied. A component-level normalize_component value overrides this
        global default. This is a component convention; the total coherent PDF
        is still normalized separately.
    normalization_resolution:
        Nominal one-dimensional Square-Dalitz resolution. For
        normalization_method="square-dalitz", this is the standard number of
        Gauss-Legendre nodes per Square-Dalitz axis before automatic narrow-
        resonance mass-axis refinement. It is also used if conventional
        Gauss-Legendre normalization switches internally to Square Dalitz for
        a narrow m12 resonance. Default: 1000.
    normalization_method:
        Normalization coordinate/integration strategy. "gauss-legendre" uses
        tensor-product Gauss-Legendre quadrature in the conventional (m13,m23)
        mass plane. "square-dalitz" uses Gauss-Legendre quadrature in
        Square-Dalitz (m-prime, theta-prime) coordinates including the
        coordinate Jacobian. "toy-mc" uses an externally supplied
        normalization sample and its event weights directly. Supplying
        normalization_sample automatically selects "toy-mc". Narrow-resonance
        adaptation applies only to the deterministic grid methods.
    normalization_pair:
        Daughter-index pair (i,j) whose invariant mass defines the Square-
        Dalitz mass coordinate. Indices follow the daughter ordering in
        channel and must be two distinct values from 0,1,2. Default: (0,1),
        corresponding to m12.
    normalization_bin_width:
        Target broad-region mass spacing in GeV for conventional
        Gauss-Legendre normalization. If explicit axis orders are not given,
        the m13 and m23 orders are their kinematic mass ranges divided by this
        value (rounded upward). It is also the coarse scale for adaptive
        conventional-DP integration. Default: 0.005 GeV (5 MeV).
    normalization_order_m13:
        Optional explicit Gauss-Legendre order along m13 for the non-adaptive
        conventional-DP grid. None means derive it from
        normalization_bin_width. Default: None.
    normalization_order_m23:
        Optional explicit Gauss-Legendre order along m23 for the non-adaptive
        conventional-DP grid. None means derive it from
        normalization_bin_width. Default: None.
    normalization_narrow_width:
        Maximum nominal resonance width in GeV for automatic narrow-resonance
        treatment. Default: 0.020 GeV (20 MeV). The classification uses the
        declared/initial resonance parameters.
    normalization_narrow_window:
        Half-width of the fine region around a narrow pole, in units of Gamma.
        The default 5.0 gives m0 +/- 5*Gamma.
    normalization_binning_factor:
        Narrow-resonance refinement factor. The target local mass spacing is
        Gamma / normalization_binning_factor. Default: 100.0, i.e. Gamma/100.
    normalization_sample:
        Optional external Monte Carlo sample used for every normalization
        integral. The package convention is mean(sample.weights * f). A
        sample must contain integration/importance weights for its proposal.
        Unit weights are appropriate only for a proposal uniform in the target
        measure (up to its volume convention), not arbitrary signal toys.
        Use sample.with_importance_weights(q) for a known proposal density q.
        A common weight scale changes the density measure; use consistent
        conventions across components and charge samples.
    normalization_chunk_size:
        ``"auto"`` (default) or a positive integer. With floating dynamics the
        normalization is accumulated in blocks of at most this many points, so
        the memory of the reverse-AD pass does not grow with the grid size.
        ``"auto"`` measures that cost on the first normalization points
        (compile-time memory of the Hessian-vector product) and picks the
        largest block that fits half of the free device memory; without device
        memory statistics (CPU) it uses 100000. An integer overrides this.
        Coefficient-only fits use blocks of 100000 points, which only amortize
        XLA compilation. The effective block width is balanced below the limit
        to minimize padding. The chunk size changes the evaluation schedule,
        not the normalization integral.

    Notes
    -----
    The narrow-resonance integration scheme is fixed from the nominal/initial
    masses and widths and is not rebuilt while those parameters float in a fit.
    """

    channel: DecayChannel
    components: tuple[Resonance | NonResonant | DalitzAmplitude, ...]
    normalize_components: bool
    normalization_resolution: int
    normalization_method: Literal["gauss-legendre", "square-dalitz", "toy-mc"]
    normalization_pair: tuple[int, int]
    normalization_bin_width: float
    normalization_order_m13: int | None
    normalization_order_m23: int | None
    normalization_narrow_width: float
    normalization_narrow_window: float
    normalization_binning_factor: float
    normalization_chunk_size: int | str
    _auto_chunk_memo: dict[tuple, int]
    _normalization_sample: PhaseSpaceSample | None
    _amplitude_model: CoherentAmplitudeModel | None
    _compact_prepare_kernels: dict[tuple[bool, bool], object]
    _compact_data_kernels: dict[bool, object]
    _fixed_normalization_templates: dict[bool, tuple[object, object]]
    _fraction_jacobian_kernels: dict[tuple, object]
    _interference_jacobian_kernels: dict[tuple, object]

    def __init__(
        self,
        channel: DecayChannel,
        components: Iterable[Resonance | NonResonant | DalitzAmplitude],
        *,
        normalize_components: bool = True,
        normalization_resolution: int = 1000,
        normalization_method: Literal["gauss-legendre", "square-dalitz", "toy-mc"] = "gauss-legendre",
        normalization_pair: tuple[int, int] = (0, 1),
        normalization_bin_width: float = 0.005,
        normalization_order_m13: int | None = None,
        normalization_order_m23: int | None = None,
        normalization_narrow_width: float = 0.020,
        normalization_narrow_window: float = 5.0,
        normalization_binning_factor: float = 100.0,
        normalization_sample: PhaseSpaceSample | None = None,
        normalization_chunk_size: int | str = "auto",
    ) -> None:
        if normalization_resolution < 2:
            raise ValueError("normalization_resolution must be at least 2")
        if normalization_method not in ("gauss-legendre", "square-dalitz", "toy-mc"):
            raise ValueError(
                "normalization_method must be 'gauss-legendre', 'square-dalitz', or 'toy-mc'"
            )
        if normalization_sample is not None:
            if not isinstance(normalization_sample, PhaseSpaceSample):
                raise TypeError("normalization_sample must be a PhaseSpaceSample")
            normalization_sample.validate_integration()
            normalization_method = "toy-mc"
        elif normalization_method == "toy-mc":
            raise ValueError(
                "normalization_method='toy-mc' requires normalization_sample"
            )
        if len(set(normalization_pair)) != 2 or any(
            index not in (0, 1, 2) for index in normalization_pair
        ):
            raise ValueError(
                "normalization_pair must contain two distinct indices from 0, 1, 2"
            )
        if normalization_bin_width <= 0.0:
            raise ValueError("normalization_bin_width must be positive")
        if normalization_order_m13 is not None and normalization_order_m13 < 2:
            raise ValueError("normalization_order_m13 must be at least 2")
        if normalization_order_m23 is not None and normalization_order_m23 < 2:
            raise ValueError("normalization_order_m23 must be at least 2")
        if normalization_narrow_width <= 0.0:
            raise ValueError("normalization_narrow_width must be positive")
        if normalization_narrow_window <= 0.0:
            raise ValueError("normalization_narrow_window must be positive")
        if normalization_binning_factor <= 0.0:
            raise ValueError("normalization_binning_factor must be positive")
        if normalization_chunk_size != "auto" and (
            isinstance(normalization_chunk_size, bool)
            or not isinstance(normalization_chunk_size, int)
            or normalization_chunk_size < 1
        ):
            raise ValueError(
                "normalization_chunk_size must be a positive integer or 'auto'"
            )
        object.__setattr__(self, "channel", channel)
        object.__setattr__(self, "components", tuple(components))
        object.__setattr__(self, "normalize_components", bool(normalize_components))
        object.__setattr__(self, "normalization_resolution", int(normalization_resolution))
        object.__setattr__(self, "normalization_method", normalization_method)
        object.__setattr__(self, "normalization_pair", tuple(normalization_pair))
        object.__setattr__(self, "normalization_bin_width", float(normalization_bin_width))
        object.__setattr__(self, "normalization_order_m13", normalization_order_m13)
        object.__setattr__(self, "normalization_order_m23", normalization_order_m23)
        object.__setattr__(
            self, "normalization_narrow_width", float(normalization_narrow_width)
        )
        object.__setattr__(
            self, "normalization_narrow_window", float(normalization_narrow_window)
        )
        object.__setattr__(
            self, "normalization_binning_factor", float(normalization_binning_factor)
        )
        object.__setattr__(self, "normalization_chunk_size", normalization_chunk_size)
        object.__setattr__(self, "_auto_chunk_memo", {})
        object.__setattr__(self, "_normalization_sample", normalization_sample)
        object.__setattr__(self, "_amplitude_model", None)
        object.__setattr__(self, "_compact_prepare_kernels", {})
        object.__setattr__(self, "_compact_data_kernels", {})
        object.__setattr__(self, "_fixed_normalization_templates", {})
        object.__setattr__(self, "_fraction_jacobian_kernels", {})
        object.__setattr__(self, "_interference_jacobian_kernels", {})
        if not self.components:
            raise ValueError("DecayModel requires at least one amplitude component")
        names = [component.name for component in self.components]
        if len(set(names)) != len(names):
            raise ValueError("DecayModel component names must be unique")
        self._validate_parameters()

    def _validate_parameters(self) -> None:
        names: dict[str, Parameter] = {}
        dynamics_slots: dict[tuple[str, str], Parameter] = {}
        for component in self.components:
            for parameter in _collect_parameters(component):
                if parameter.name in names and names[parameter.name] != parameter:
                    raise ValueError(f"Conflicting definitions for parameter {parameter.name!r}")
                names[parameter.name] = parameter
                if parameter.kind is ParameterKind.DYNAMICS:
                    if parameter.owner != component.name:
                        raise ValueError(
                            f"Dynamics parameter {parameter.name!r} must have owner={component.name!r}"
                        )
                    backend_key = parameter.backend_name or parameter.name
                    slot = (component.name, backend_key)
                    previous = dynamics_slots.get(slot)
                    if previous is not None and previous.name != parameter.name:
                        raise ValueError(
                            "Dynamics parameters "
                            f"{previous.name!r} and {parameter.name!r} map to the same "
                            f"backend key {backend_key!r} for component {component.name!r}"
                        )
                    dynamics_slots[slot] = parameter
                if parameter.kind is ParameterKind.COEFFICIENT and parameter.owner is not None and parameter.owner != component.name:
                    raise ValueError(
                        f"Coefficient parameter {parameter.name!r} must have owner={component.name!r}"
                    )

    def _adaptive_narrow_resonances(
        self,
    ) -> dict[str, tuple[tuple[float, float], ...]]:
        """Find Laura++-style narrow bands using nominal resonance parameters.

        The integration scheme is deliberately fixed from the declared/initial
        mass and width values, matching Laura++ behaviour.  Identical-particle
        symmetrisation is expanded so a single declared resonance can refine
        more than one invariant-mass axis.
        """

        result: dict[str, set[tuple[float, float]]] = {
            "m12": set(),
            "m13": set(),
            "m23": set(),
        }
        pair_to_axis = {
            (0, 1): "m12",
            (0, 2): "m13",
            (1, 2): "m23",
        }
        masses = self.channel.daughter_masses
        final_state_ids = self.channel.final_state_ids

        for component in self.components:
            if not isinstance(component, Resonance):
                continue

            resolved_mass, resolved_width, _ = _resolved_resonance_properties(
                component
            )
            nominal_mass = _nominal_float(resolved_mass, 0.0)
            nominal_width = _nominal_float(resolved_width, 0.0)
            if (
                nominal_width <= 0.0
                or nominal_width > self.normalization_narrow_width
            ):
                continue

            for pair in _symmetrized_mass_pairs(component.pair, final_state_ids):
                bachelor = next(index for index in range(3) if index not in pair)
                low = masses[pair[0]] + masses[pair[1]]
                high = self.channel.parent_mass - masses[bachelor]
                if nominal_mass < low or nominal_mass > high:
                    continue
                result[pair_to_axis[pair]].add((nominal_mass, nominal_width))

        return {
            axis: tuple(sorted(values))
            for axis, values in result.items()
        }

    def _flatten_narrow_resonances(
        self,
        narrow: dict[str, tuple[tuple[float, float], ...]] | None = None,
    ) -> tuple[tuple[tuple[int, int], float, float], ...]:
        """Return unique narrow bands as (pair, pole_mass, pole_width)."""

        values = self._adaptive_narrow_resonances() if narrow is None else narrow
        axis_to_pair = {
            "m12": (0, 1),
            "m13": (0, 2),
            "m23": (1, 2),
        }
        flattened = []
        for axis, pair in axis_to_pair.items():
            for mass, width in values[axis]:
                flattened.append((pair, mass, width))
        return tuple(flattened)

    @staticmethod
    def _format_narrow_bands(
        narrow: dict[str, tuple[tuple[float, float], ...]],
    ) -> str:
        entries = []
        for axis in ("m12", "m13", "m23"):
            for mass, width in narrow[axis]:
                entries.append(
                    f"{axis}: m0={mass:.6f} GeV, Gamma={1000.0 * width:.3f} MeV"
                )
        return "; ".join(entries)

    @property
    def normalization_scheme(self) -> dict[str, object]:
        """Describe the active normalization strategy."""

        if self.normalization_method == "toy-mc":
            sample = self.normalization_sample
            return {
                "method": "toy-mc",
                "adaptive": False,
                "sample_size": sample.size,
                "weighted": bool(jnp.any(jnp.asarray(sample.weights) != 1.0)),
                "chunk_size": self.normalization_chunk_size,
            }

        narrow = self._adaptive_narrow_resonances()
        has_narrow = any(narrow[axis] for axis in ("m12", "m13", "m23"))

        if not has_narrow:
            if self.normalization_method == "gauss-legendre":
                return {
                    "method": "gauss-legendre",
                    "adaptive": False,
                    "bin_width": self.normalization_bin_width,
                    "order_m13": self.normalization_order_m13,
                    "order_m23": self.normalization_order_m23,
                }
            return {
                "method": "square-dalitz",
                "adaptive": False,
                "pair": self.normalization_pair,
                "resolution": self.normalization_resolution,
            }

        if self.normalization_method == "gauss-legendre" and not narrow["m12"]:
            grid = AdaptiveDalitzGaussLegendreGrid(
                self.channel.parent_mass,
                self.channel.daughter_masses,
                m13_narrow_resonances=narrow["m13"],
                m23_narrow_resonances=narrow["m23"],
                bin_width=self.normalization_bin_width,
                narrow_width=self.normalization_narrow_width,
                window_n_widths=self.normalization_narrow_window,
                binning_factor=self.normalization_binning_factor,
            )
            return {
                "method": "gauss-legendre",
                "adaptive": True,
                "internal_coordinates": "m13-m23",
                "narrow_resonances": narrow,
                "m13_segments": grid.m13_segments,
                "m23_segments": grid.m23_segments,
                "estimated_tensor_points": grid.estimated_tensor_points,
            }

        if self.normalization_method == "gauss-legendre":
            return {
                "method": "gauss-legendre",
                "adaptive": True,
                "internal_coordinates": "square-dalitz",
                "reason": "narrow m12 band is diagonal in the conventional m13-m23 plane",
                "pair": (0, 1),
                "resolution": self.normalization_resolution,
                "narrow_resonances": narrow,
            }

        square_grid = AdaptiveSquareDalitzGrid(
            self.channel.parent_mass,
            self.channel.daughter_masses,
            narrow_resonances=self._flatten_narrow_resonances(narrow),
            resolution=self.normalization_resolution,
            pair=self.normalization_pair,
            window_n_widths=self.normalization_narrow_window,
            binning_factor=self.normalization_binning_factor,
        )
        return {
            "method": "square-dalitz",
            "adaptive": bool(square_grid.aligned_narrow_resonances),
            "adaptive_axis": "mprime",
            "pair": self.normalization_pair,
            "theta_resolution": self.normalization_resolution,
            "mprime_nodes": square_grid.mprime_node_count,
            "estimated_points": square_grid.estimated_points,
            "aligned_narrow_resonances": square_grid.aligned_narrow_resonances,
            "crossed_narrow_resonances": square_grid.crossed_narrow_resonances,
            "narrow_resonances": narrow,
        }

    @property
    def parameters(self) -> tuple[Parameter, ...]:
        """All `Parameter`s referenced by `components`, deduplicated by name."""
        unique: dict[str, Parameter] = {}
        for component in self.components:
            for parameter in _collect_parameters(component):
                unique.setdefault(parameter.name, parameter)
        return tuple(unique.values())

    def with_fixed_parameters(
        self,
        *names: str,
        values: Mapping[str, float] | None = None,
    ) -> DecayModel:
        """Return a new model with selected parameters fixed.

        Positional names retain their current values. Entries in ``values``
        are assigned the supplied value and fixed. The original model and its
        parameters remain unchanged.
        """
        updates = _fixed_parameter_updates(self.parameters, names, values)
        components = _replace_fixed_parameters(self.components, updates)
        normalization_sample = (
            self._normalization_sample
            if self.normalization_method == "toy-mc"
            else None
        )
        return DecayModel(
            self.channel,
            components,
            normalize_components=self.normalize_components,
            normalization_resolution=self.normalization_resolution,
            normalization_method=self.normalization_method,
            normalization_pair=self.normalization_pair,
            normalization_bin_width=self.normalization_bin_width,
            normalization_order_m13=self.normalization_order_m13,
            normalization_order_m23=self.normalization_order_m23,
            normalization_narrow_width=self.normalization_narrow_width,
            normalization_narrow_window=self.normalization_narrow_window,
            normalization_binning_factor=self.normalization_binning_factor,
            normalization_sample=normalization_sample,
            normalization_chunk_size=self.normalization_chunk_size,
        )

    @property
    def normalization_sample(self) -> PhaseSpaceSample:
        """Deterministic quadrature sample used to normalize the amplitude model.

        Built lazily from `normalization_method` (with automatic narrow-resonance
        grid refinement) and cached on first access.
        """
        sample = self._normalization_sample
        if sample is None:
            narrow = self._adaptive_narrow_resonances()
            has_narrow = any(
                narrow[axis] for axis in ("m12", "m13", "m23")
            )

            if self.normalization_method == "gauss-legendre":
                if not has_narrow:
                    sample = DalitzGaussLegendreGrid(
                        self.channel.parent_mass,
                        self.channel.daughter_masses,
                        bin_width=self.normalization_bin_width,
                        order_m13=self.normalization_order_m13,
                        order_m23=self.normalization_order_m23,
                    ).sample()
                elif narrow["m12"]:
                    grid = AdaptiveSquareDalitzGrid(
                        self.channel.parent_mass,
                        self.channel.daughter_masses,
                        narrow_resonances=self._flatten_narrow_resonances(narrow),
                        resolution=self.normalization_resolution,
                        pair=(0, 1),
                        window_n_widths=self.normalization_narrow_window,
                        binning_factor=self.normalization_binning_factor,
                    )
                    print(
                        "INFO Jax-PWA normalization: narrow resonance "
                        "band(s) detected ("
                        + self._format_narrow_bands(narrow)
                        + "); using Square-Dalitz coordinates internally because "
                        "m12 is diagonal in the conventional m13-m23 plane. "
                        "Adaptive refinement is applied only along the mass "
                        f"axis m': {grid.mprime_node_count} m' nodes x "
                        f"{self.normalization_resolution} theta' nodes "
                        f"({grid.estimated_points:,} points)."
                    )
                    sample = grid.sample()
                else:
                    print(
                        "INFO Jax-PWA normalization: narrow resonance "
                        "band(s) detected ("
                        + self._format_narrow_bands(narrow)
                        + "); using adaptive Gauss-Legendre normalization."
                    )
                    sample = AdaptiveDalitzGaussLegendreGrid(
                        self.channel.parent_mass,
                        self.channel.daughter_masses,
                        m13_narrow_resonances=narrow["m13"],
                        m23_narrow_resonances=narrow["m23"],
                        bin_width=self.normalization_bin_width,
                        narrow_width=self.normalization_narrow_width,
                        window_n_widths=self.normalization_narrow_window,
                        binning_factor=self.normalization_binning_factor,
                    ).sample()
            else:
                if not has_narrow:
                    sample = SquareDalitzGrid(
                        self.channel.parent_mass,
                        self.channel.daughter_masses,
                        resolution=self.normalization_resolution,
                        pair=self.normalization_pair,
                        quadrature="gauss-legendre",
                    ).sample()
                else:
                    grid = AdaptiveSquareDalitzGrid(
                        self.channel.parent_mass,
                        self.channel.daughter_masses,
                        narrow_resonances=self._flatten_narrow_resonances(narrow),
                        resolution=self.normalization_resolution,
                        pair=self.normalization_pair,
                        window_n_widths=self.normalization_narrow_window,
                        binning_factor=self.normalization_binning_factor,
                    )
                    if grid.aligned_narrow_resonances:
                        print(
                            "INFO Jax-PWA normalization: narrow resonance "
                            "band(s) detected ("
                            + self._format_narrow_bands(narrow)
                            + "); applying adaptive Square-Dalitz refinement only "
                            "along the mass axis m'. "
                            f"Grid: {grid.mprime_node_count} m' nodes x "
                            f"{self.normalization_resolution} theta' nodes "
                            f"({grid.estimated_points:,} points; base "
                            f"{self.normalization_resolution**2:,})."
                        )
                        if grid.crossed_narrow_resonances:
                            print(
                                "INFO Jax-PWA normalization: crossed narrow "
                                "band(s) are kept on the standard theta' resolution; "
                                "only resonances aligned with normalization_pair "
                                "refine m'."
                            )
                        sample = grid.sample()
                    else:
                        print(
                            "INFO Jax-PWA normalization: narrow resonance "
                            "band(s) detected, but none is aligned with the selected "
                            "Square-Dalitz mass pair; keeping the standard "
                            f"{self.normalization_resolution} x "
                            f"{self.normalization_resolution} grid."
                        )
                        sample = SquareDalitzGrid(
                            self.channel.parent_mass,
                            self.channel.daughter_masses,
                            resolution=self.normalization_resolution,
                            pair=self.normalization_pair,
                            quadrature="gauss-legendre",
                        ).sample()

            object.__setattr__(self, "_normalization_sample", sample)
        return sample

    def _build_resonance(self, component: Resonance) -> AmplitudeComponent:
        i, j = component.pair
        bachelor = next(index for index in range(3) if index not in component.pair)
        masses = self.channel.daughter_masses
        mass0, width0, spin = _resolved_resonance_properties(component)
        context = ResonanceContext(
            parent_mass=self.channel.parent_mass,
            daughter_masses=(masses[i], masses[j]),
            bachelor_mass=masses[bachelor],
            spin=spin,
            pole_mass=mass0,
            pole_width=width0,
            resonance_radius=component.resonance_radius,
            parent_radius=component.parent_radius,
        )
        dynamics = ResonanceAmplitude(
            context=context,
            daughter_key=f"p{i + 1}",
            partner_key=f"p{j + 1}",
            bachelor_key=f"p{bachelor + 1}",
            final_state=self.channel.final_state_ids,
            lineshape=component.lineshape,
            angular=component.angular,
            bachelor_momentum_frame=component.bachelor_momentum_frame,
            normalize_form_factors=component.normalize_form_factors,
        )
        return AmplitudeComponent(
            component.name,
            dynamics,
            component.coefficient,
            component.normalize_component,
        )

    @property
    def amplitude_model(self) -> CoherentAmplitudeModel:
        """Built `CoherentAmplitudeModel`, resolving each declared component's dynamics.

        Built lazily from `components` (`Resonance`, `NonResonant`, `DalitzAmplitude`)
        and cached on first access.
        """
        model = self._amplitude_model
        if model is not None:
            return model
        built = []
        for component in self.components:
            if isinstance(component, Resonance):
                built.append(self._build_resonance(component))
            elif isinstance(component, NonResonant):
                built.append(
                    AmplitudeComponent(
                        component.name,
                        ConstantAmplitude(),
                        component.coefficient,
                        component.normalize_component,
                    )
                )
            elif isinstance(component, DalitzAmplitude):
                built.append(
                    AmplitudeComponent(
                        component.name,
                        _ResolvedDirectDynamics(component.dynamics),
                        component.coefficient,
                        component.normalize_component,
                    )
                )
            else:
                raise TypeError(f"Unsupported amplitude component: {type(component)!r}")
        model = CoherentAmplitudeModel(tuple(built))
        object.__setattr__(self, "_amplitude_model", model)
        return model

    def _compact_prepare_kernel(self, *, normalize_components: bool, has_efficiency: bool):
        key = (bool(normalize_components), bool(has_efficiency))
        kernel = self._compact_prepare_kernels.get(key)
        if kernel is None:
            kernel = PreparedAmplitudeCache.build_compact_prepare_kernel(
                self.amplitude_model.components,
                normalize_components=normalize_components,
                has_efficiency=has_efficiency,
                compact_data_kernel=self._compact_data_kernel(
                    normalize_components=normalize_components,
                ),
                normalization_chunk_size=(
                    DEFAULT_NORMALIZATION_CHUNK_SIZE
                    if self.normalization_chunk_size == "auto"
                    else self.normalization_chunk_size
                ),
            )
            self._compact_prepare_kernels[key] = kernel
        return kernel

    def _compact_data_kernel(self, *, normalize_components: bool):
        key = bool(normalize_components)
        kernel = self._compact_data_kernels.get(key)
        if kernel is None:
            kernel = PreparedAmplitudeCache.build_compact_data_kernel(
                self.amplitude_model.components,
                normalize_components=normalize_components,
            )
            self._compact_data_kernels[key] = kernel
        return kernel

    def generate_phase_space(
        self,
        size: int,
        *,
        seed: int | None = None,
        include_momenta: bool = True,
    ) -> PhaseSpaceSample:
        """Generate a uniform-in-phase-space toy sample for `channel`."""
        return PhaseSpaceMC(
            self.channel.parent_mass,
            self.channel.daughter_masses,
        ).generate(
            size,
            seed=seed,
            include_momenta=include_momenta,
        )

    def generate_stratified_phase_space(
        self,
        size: int,
        *,
        cell_probabilities,
        grid_shape: tuple[int, int],
        seed: int | None = None,
        integration_weights: bool = True,
    ):
        """Generate stratified phase space; integration weights are the default.

        Set integration_weights=False only for accept-reject proposals.
        """

        return PhaseSpaceMC(
            self.channel.parent_mass,
            self.channel.daughter_masses,
        ).generate_stratified_invariants(
            size,
            cell_probabilities=cell_probabilities,
            grid_shape=grid_shape,
            seed=seed,
            integration_weights=integration_weights,
        )

    def _component_scale(self, component: AmplitudeComponent, values=None):
        normalize = (
            self.normalize_components
            if component.normalize_component is None
            else component.normalize_component
        )
        if not normalize:
            return 1.0
        sample = self.normalization_sample
        raw = jnp.asarray(component.function(sample.as_dict(), values))
        integral = jnp.mean(sample.weights * jnp.abs(raw) ** 2)
        return 1.0 / jnp.sqrt(integral)

    def component_amplitudes(self, data, values=None) -> dict:
        """Each component's coefficient-scaled amplitude at `data`, keyed by name.

        The terms ``amplitude()`` sums coherently: ``|component|^2`` is the
        incoherent contribution of one component (e.g. for drawing it on a
        projection), and the coherent total minus the sum of these is the
        interference.
        """
        result = {}
        for component in self.amplitude_model.components:
            dynamics = jnp.asarray(component.function(data, values))
            coefficient = jnp.asarray(coefficient_value(component.coefficient, values))
            result[component.name] = coefficient * self._component_scale(component, values) * dynamics
        return result

    def amplitude(self, data, values=None):
        """Coherent sum of every component's coefficient-scaled dynamics at `data`."""
        total = None
        for component_values in self.component_amplitudes(data, values).values():
            total = component_values if total is None else total + component_values
        return jnp.asarray(total)

    def intensity(self, data, values=None):
        """Squared magnitude of `amplitude` at `data`, i.e. |A|^2."""
        amplitude = self.amplitude(data, values)
        return jnp.real(amplitude * jnp.conj(amplitude))

    def pdf(self, normalization_sample: PhaseSpaceSample | None = None, *, efficiency=None) -> SignalPDF:
        """Build a `SignalPDF` for this model, normalized on `normalization_sample`.

        Defaults to `self.normalization_sample`; an explicit sample is validated
        as a proper integration sample first.
        """
        sample = self.normalization_sample if normalization_sample is None else normalization_sample
        if normalization_sample is not None:
            sample.validate_integration()
        def intensity(data, parameters):
            return self.intensity(data, parameters)
        kwargs = {}
        if efficiency is not None:
            kwargs["efficiency"] = efficiency
        return SignalPDF(intensity=intensity, integrator=GridIntegrator(sample), **kwargs)

    def prepare_cache(
        self,
        data_sample: PhaseSpaceSample,
        normalization_sample: PhaseSpaceSample | None = None,
        *,
        efficiency_normalization=None,
        normalize_components: bool | None = None,
    ) -> PreparedAmplitudeCache:
        """Build a `PreparedAmplitudeCache` for `data_sample` against this model.

        Reuses a cached fixed component-scale/normalization-matrix template
        when nothing floating can change it (no floating dynamics parameters,
        no efficiency normalization, and the default `normalization_sample`).
        """
        sample = self.normalization_sample if normalization_sample is None else normalization_sample
        if normalization_sample is not None:
            sample.validate_integration()
        normalize = self.normalize_components if normalize_components is None else bool(normalize_components)
        has_floating_dynamics = any(
            parameter.kind is ParameterKind.DYNAMICS and not parameter.fixed
            for parameter in self.parameters
        )

        # The common coefficient-only/no-efficiency case has a normalization
        # that depends only on the model and its fixed quadrature sample. Cache
        # the tiny scales and M_ij once, then later FitSessions evaluate only the
        # new dataset amplitudes.
        template_key = bool(normalize)
        can_reuse_normalization = (
            not has_floating_dynamics
            and efficiency_normalization is None
            and sample is self.normalization_sample
        )
        if can_reuse_normalization:
            template = self._fixed_normalization_templates.get(template_key)
            if template is not None:
                scales, matrix = template
                return PreparedAmplitudeCache.prepare_from_fixed_normalization(
                    self.amplitude_model.components,
                    data=data_sample.as_dict(),
                    normalization_weights=sample.weights,
                    parameters=self.parameters,
                    normalization_matrix_fixed=matrix,
                    component_scales=scales,
                    normalize_components=normalize,
                    compact_data_kernel=self._compact_data_kernel(
                        normalize_components=normalize
                    ),
                )

        compact_kernel = None
        if not has_floating_dynamics:
            compact_kernel = self._compact_prepare_kernel(
                normalize_components=normalize,
                has_efficiency=efficiency_normalization is not None,
            )
        cache = PreparedAmplitudeCache.prepare(
            self.amplitude_model.components,
            data=data_sample.as_dict(),
            normalization_data=sample.as_dict(),
            normalization_weights=sample.weights,
            parameters=self.parameters,
            efficiency_normalization=efficiency_normalization,
            normalize_components=normalize,
            compact_prepare_kernel=compact_kernel,
            normalization_chunk_size=self.normalization_chunk_size,
            chunk_size_memo=self._auto_chunk_memo,
        )
        if can_reuse_normalization:
            self._fixed_normalization_templates[template_key] = (
                cache.component_scales,
                cache.normalization_matrix_fixed,
            )
        return cache

    def _fraction_cache(
        self,
        normalization_sample: PhaseSpaceSample | None,
        efficiency,
    ) -> PreparedAmplitudeCache:
        sample = (
            self.normalization_sample
            if normalization_sample is None
            else normalization_sample
        )
        efficiency_values = None
        if efficiency is not None:
            efficiency_values = (
                efficiency(sample.as_dict()) if callable(efficiency) else efficiency
            )
            efficiency_values = jnp.asarray(efficiency_values)
            if efficiency_values.shape != (sample.size,):
                raise ValueError(
                    "efficiency must return one value per normalization point"
                )
        # Fit fractions use only the normalization matrix. The cache API also
        # prepares data amplitudes, so supply just one real event on that side
        # instead of duplicating the entire integration sample's preparation.
        # Keep the full normalization sample and its integration weights intact.
        data_sample = sample.take(jnp.arange(min(sample.size, 1), dtype=jnp.int32))
        return self.prepare_cache(
            data_sample,
            normalization_sample=sample,
            efficiency_normalization=efficiency_values,
        )

    def fit_fractions(
        self,
        fit_values=None,
        *,
        normalization_sample: PhaseSpaceSample | None = None,
        efficiency=None,
    ):
        """Return component fit fractions at a parameter point.

        Fractions are physical (efficiency excluded) by default. Supplying an
        efficiency returns acceptance-weighted fractions instead.
        """

        values = {} if fit_values is None else fit_values
        return self._fraction_cache(
            normalization_sample, efficiency
        ).fit_fractions(values)

    def interference_fractions(
        self,
        fit_values=None,
        *,
        normalization_sample: PhaseSpaceSample | None = None,
        efficiency=None,
    ):
        """Return pairwise interference fractions at a parameter point."""

        values = {} if fit_values is None else fit_values
        return self._fraction_cache(
            normalization_sample, efficiency
        ).interference_fractions(values)

    def print_fit_fractions(
        self,
        fit_values=None,
        *,
        normalization_sample: PhaseSpaceSample | None = None,
        efficiency=None,
        include_interference: bool = False,
        precision: int = 3,
        with_errors: bool = False,
        covariance=None,
        parameter_names: Sequence[str] | None = None,
    ) -> dict[str, float] | dict[str, object]:
        """Print fit fractions as percentages and return them by component name.

        ``with_errors=True`` -- the same flag ``FitSession``/``CPFitSession``/
        ``TimeDependentFitSession.print_fit_fractions`` expose -- additionally
        computes and prints each fraction's (and, with
        ``include_interference=True``, each interference term's) delta-method
        standard error via ``fit_fraction_errors()``/
        ``interference_fraction_errors()``, requiring a postfit ``covariance``
        (e.g. ``result.covariance`` from ``Minimizer.fit``); ``parameter_names``
        is forwarded to those methods unchanged.

        With ``with_errors=False`` and no ``include_interference``, the
        return value is the plain ``{component_name: fraction}`` dict
        (backward compatible with the no-error, no-interference call). As
        soon as either is requested, the return value instead becomes
        ``{"fractions": ..., "errors": ...?, "interference": ...?,
        "interference_errors": ...?}``, each optional key present only when
        the corresponding input was supplied/requested.
        """

        if precision < 0:
            raise ValueError("precision must be non-negative")
        if with_errors and covariance is None:
            raise ValueError("with_errors=True requires covariance")
        values = {} if fit_values is None else fit_values
        errors = (
            self.fit_fraction_errors(
                values,
                covariance,
                parameter_names,
                normalization_sample=normalization_sample,
                efficiency=efficiency,
            )
            if with_errors
            else None
        )
        interference_errors = (
            self.interference_fraction_errors(
                values,
                covariance,
                parameter_names,
                normalization_sample=normalization_sample,
                efficiency=efficiency,
            )
            if with_errors and include_interference
            else None
        )
        cache = self._fraction_cache(normalization_sample, efficiency)
        fractions = cache.fit_fractions(values)
        result = {
            component.name: float(fractions[index])
            for index, component in enumerate(cache.components)
        }
        convention = "acceptance-weighted" if efficiency is not None else "physical"
        print(f"Fit fractions ({convention})")
        if errors is None:
            print(f"{'component':24s} {'fraction [%]':>16s}")
            for name, fraction in result.items():
                print(f"{name:24s} {100.0 * fraction:16.{precision}f}")
            print(f"{'sum':24s} {100.0 * sum(result.values()):16.{precision}f}")
        else:
            print(f"{'component':24s} {'fraction [%]':>16s} {'error [%]':>16s}")
            for name, fraction in result.items():
                print(
                    f"{name:24s} {100.0 * fraction:16.{precision}f} "
                    f"{100.0 * errors.get(name, 0.0):16.{precision}f}"
                )
            print(f"{'sum':24s} {100.0 * sum(result.values()):16.{precision}f}")

        interference_result: dict[tuple[str, str], float] = {}
        if include_interference:
            interference = cache.interference_fractions(values)
            print("\nInterference fractions")
            if interference_errors is None:
                print(f"{'pair':49s} {'fraction [%]':>16s}")
            else:
                print(f"{'pair':49s} {'fraction [%]':>16s} {'error [%]':>16s}")
            for i, first in enumerate(cache.components):
                for j in range(i + 1, len(cache.components)):
                    second = cache.components[j]
                    fraction = float(interference[i, j])
                    interference_result[(first.name, second.name)] = fraction
                    if interference_errors is None:
                        print(
                            f"{first.name + ' x ' + second.name:49s} "
                            f"{100.0 * fraction:16.{precision}f}"
                        )
                    else:
                        error = interference_errors.get((first.name, second.name), 0.0)
                        print(
                            f"{first.name + ' x ' + second.name:49s} "
                            f"{100.0 * fraction:16.{precision}f} "
                            f"{100.0 * error:16.{precision}f}"
                        )

        # Plain fraction-only return by default (backward compatible); the
        # return value only grows a wrapping dict once there is something
        # extra -- errors and/or interference -- to attach to it.
        if errors is None and not include_interference:
            return result

        output: dict[str, object] = {"fractions": result}
        if errors is not None:
            output["errors"] = errors
        if include_interference:
            output["interference"] = interference_result
            if interference_errors is not None:
                output["interference_errors"] = interference_errors
        return output

    def fit_fraction_errors(
        self,
        fit_values,
        covariance,
        parameter_names: Sequence[str] | None = None,
        *,
        normalization_sample: PhaseSpaceSample | None = None,
        efficiency=None,
    ) -> dict[str, float]:
        """Delta-method standard errors for ``fit_fractions()``.

        ``fit_values`` are the postfit parameter values (e.g. from
        ``FitSession.result_values``/``CPFitSession.result_values``);
        entries missing from it fall back to each ``Parameter``'s own
        declared value, exactly like ``fit_fractions()``/
        ``print_fit_fractions()``. ``covariance`` is a postfit covariance
        matrix -- typically an ``iminuit`` ``Minuit.covariance`` (e.g.
        ``result.covariance`` from ``Minimizer.fit``) -- restricted
        internally to ``parameter_names``, which defaults to every
        non-fixed parameter in ``self.parameters``. ``normalization_sample``
        and ``efficiency`` select the same physical-vs-acceptance-weighted
        convention as ``fit_fractions()``.

        This is a linear (Gaussian) error-propagation approximation, exactly
        the one implicit in Minuit's own HESSE errors; see
        ``jaxpwa.observables.delta_method_errors``.
        """
        if parameter_names is None:
            parameter_names = tuple(
                parameter.name for parameter in self.parameters if not parameter.fixed
            )
        values = {
            parameter.name: parameter.resolve(fit_values) for parameter in self.parameters
        }
        cache = self._fraction_cache(normalization_sample, efficiency)
        jacobian = self._fraction_jacobian(cache, values, parameter_names)
        matrix = _covariance_matrix(covariance, parameter_names)
        variance = jnp.diag(jacobian @ matrix @ jacobian.T)
        errors = jnp.sqrt(jnp.clip(variance, 0.0))
        return {
            component.name: float(errors[index])
            for index, component in enumerate(cache.components)
        }

    def _fraction_jacobian(self, cache, values, parameter_names, quantity="fit_fractions"):
        names = tuple(parameter_names)
        key = (names, cache.normalize_components, cache._component_partitions(), quantity)
        kernel = self._fraction_jacobian_kernels.get(key)
        if kernel is None:
            kernel = cache._build_fraction_jacobian_kernel(names, quantity)
            self._fraction_jacobian_kernels[key] = kernel
        return kernel(values, cache._fraction_jacobian_arrays())

    def interference_fraction_errors(
        self,
        fit_values,
        covariance,
        parameter_names: Sequence[str] | None = None,
        *,
        normalization_sample: PhaseSpaceSample | None = None,
        efficiency=None,
    ) -> dict[tuple[str, str], float]:
        """Delta-method standard errors for ``interference_fractions()``.

        Same convention as ``fit_fraction_errors()`` (same ``fit_values``/
        ``covariance``/``parameter_names`` semantics, same linear-propagation
        caveat), but for the pairwise interference terms instead of the
        per-component fractions. Returned dict is keyed by
        ``(name_i, name_j)`` for every ``i < j`` pair in component order.
        """
        if parameter_names is None:
            parameter_names = tuple(
                parameter.name for parameter in self.parameters if not parameter.fixed
            )
        values = {
            parameter.name: parameter.resolve(fit_values) for parameter in self.parameters
        }
        cache = self._fraction_cache(normalization_sample, efficiency)
        jacobian, pairs = self._interference_jacobian(cache, values, parameter_names)
        matrix = _covariance_matrix(covariance, parameter_names)
        variance = jnp.diag(jacobian @ matrix @ jacobian.T)
        errors = jnp.sqrt(jnp.clip(variance, 0.0))
        return {
            (cache.components[i].name, cache.components[j].name): float(errors[index])
            for index, (i, j) in enumerate(pairs)
        }

    def _interference_jacobian(self, cache, values, parameter_names):
        names = tuple(parameter_names)
        key = (names, cache.normalize_components, cache._component_partitions())
        entry = self._interference_jacobian_kernels.get(key)
        if entry is None:
            entry = cache._build_interference_jacobian_kernel(names)
            self._interference_jacobian_kernels[key] = entry
        kernel, pairs = entry
        return kernel(values, cache._fraction_jacobian_arrays()), pairs
